config/routes.rb
Rails.application.routes.draw do
  resources :copyrights
  resources :works
  resources :authors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/copyright.rb
class Copyright < ApplicationRecord
end

app/models/work.rb
class Work < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :see_also)
    end
end

app/controllers/copyrights_controller.rb
class CopyrightsController < ApplicationController
  before_action :set_copyright, only: [:show, :edit, :update, :destroy]

  # GET /copyrights
  # GET /copyrights.json
  def index
    @copyrights = Copyright.all
  end

  # GET /copyrights/1
  # GET /copyrights/1.json
  def show
  end

  # GET /copyrights/new
  def new
    @copyright = Copyright.new
  end

  # GET /copyrights/1/edit
  def edit
  end

  # POST /copyrights
  # POST /copyrights.json
  def create
    @copyright = Copyright.new(copyright_params)

    respond_to do |format|
      if @copyright.save
        format.html { redirect_to @copyright, notice: 'Copyright was successfully created.' }
        format.json { render :show, status: :created, location: @copyright }
      else
        format.html { render :new }
        format.json { render json: @copyright.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /copyrights/1
  # PATCH/PUT /copyrights/1.json
  def update
    respond_to do |format|
      if @copyright.update(copyright_params)
        format.html { redirect_to @copyright, notice: 'Copyright was successfully updated.' }
        format.json { render :show, status: :ok, location: @copyright }
      else
        format.html { render :edit }
        format.json { render json: @copyright.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /copyrights/1
  # DELETE /copyrights/1.json
  def destroy
    @copyright.destroy
    respond_to do |format|
      format.html { redirect_to copyrights_url, notice: 'Copyright was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_copyright
      @copyright = Copyright.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def copyright_params
      params.require(:copyright).permit(:date, :ref_number, :applicant_name, :work)
    end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:name, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/copyrights_helper.rb
module CopyrightsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :see_also %>
    <%= form.number_field :see_also %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>See also</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.see_also %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>See also:</strong>
  <%= @author.see_also %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/copyrights/_form.html.erb
<%= form_with(model: copyright, local: true) do |form| %>
  <% if copyright.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(copyright.errors.count, "error") %> prohibited this copyright from being saved:</h2>

      <ul>
        <% copyright.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :ref_number %>
    <%= form.text_field :ref_number %>
  </div>

  <div class="field">
    <%= form.label :applicant_name %>
    <%= form.text_field :applicant_name %>
  </div>

  <div class="field">
    <%= form.label :work %>
    <%= form.number_field :work %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/copyrights/edit.html.erb
<h1>Editing Copyright</h1>

<%= render 'form', copyright: @copyright %>

<%= link_to 'Show', @copyright %> |
<%= link_to 'Back', copyrights_path %>

app/views/copyrights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Copyrights</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Ref number</th>
      <th>Applicant name</th>
      <th>Work</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @copyrights.each do |copyright| %>
      <tr>
        <td><%= copyright.date %></td>
        <td><%= copyright.ref_number %></td>
        <td><%= copyright.applicant_name %></td>
        <td><%= copyright.work %></td>
        <td><%= link_to 'Show', copyright %></td>
        <td><%= link_to 'Edit', edit_copyright_path(copyright) %></td>
        <td><%= link_to 'Destroy', copyright, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Copyright', new_copyright_path %>

app/views/copyrights/new.html.erb
<h1>New Copyright</h1>

<%= render 'form', copyright: @copyright %>

<%= link_to 'Back', copyrights_path %>

app/views/copyrights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @copyright.date %>
</p>

<p>
  <strong>Ref number:</strong>
  <%= @copyright.ref_number %>
</p>

<p>
  <strong>Applicant name:</strong>
  <%= @copyright.applicant_name %>
</p>

<p>
  <strong>Work:</strong>
  <%= @copyright.work %>
</p>

<%= link_to 'Edit', edit_copyright_path(@copyright) %> |
<%= link_to 'Back', copyrights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RenewDB</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/works/_form.html.erb
<%= form_with(model: work, local: true) do |form| %>
  <% if work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
        <% work.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.number_field :author %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Works</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.name %></td>
        <td><%= work.author %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @work.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @work.author %>
</p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>